{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kazi-ancestry.fullname" . }}
  labels:
    {{- include "kazi-ancestry.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGPASSWORD: {{ .Values.database.password | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.oauth.clientSecret | quote }}
  SESSION_SECRET: {{ .Values.oauth.sessionSecret | quote }}
{{- end }}
